#!/bin/bash
# RT3000 Machine-B — PRODUCTION CONFIG-PATH regression suite (RC1-HW-002).
#
# The derivation suite (run_mac_tests.sh) proves the MAC algorithm.  It cannot
# catch a broken *propagation* path: RC1-HW-002 shipped a board.json that carried
# the correct MACs while the live interfaces kept kernel defaults, because the
# helper used (ucidef_set_network_device_mac) writes a "network-device" object
# that this tree's /bin/config_generate never reads.
#
# These tests therefore check the plumbing, distinct from the algorithm:
#   * the board.d hook uses a primitive that config_generate actually consumes
#   * config_generate still contains the consumer for it
#   * the live UCI device model is the one netifd applies
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
TOP="$(cd "$HERE/../../.." && pwd)"
HOOK="$TOP/target/linux/ipq50xx/base-files/etc/board.d/02_macaddr"
GEN="$TOP/package/base-files/files/bin/config_generate"
HELP="$TOP/package/base-files/files/lib/functions/uci-defaults.sh"
PASS=0; FAIL=0; FAILED=""
ok(){ PASS=$((PASS+1)); printf 'PASS  %s\n' "$1"; }
bad(){ FAIL=$((FAIL+1)); FAILED="$FAILED
  $1"; printf 'FAIL  %s   -- %s\n' "$1" "${2:-}"; }

echo "=== RT3000 production MAC config-path suite (RC1-HW-002) ==="
echo "hook: $HOOK"
echo

[ -f "$HOOK" ] || { echo "FATAL: hook missing"; exit 1; }

# 1. The hook must use the primitive that config_generate consumes.
if grep -q 'ucidef_set_interface_macaddr' "$HOOK"; then
	ok "hook uses ucidef_set_interface_macaddr (a consumed primitive)"
else
	bad "consumed primitive" "hook does not call ucidef_set_interface_macaddr"
fi

# 2. ...and it must do so for lan and wan, which are the interface names this
#    board's 02_network generates.
if grep -q 'ucidef_set_interface_macaddr lan'  "$HOOK" && \
   grep -q 'ucidef_set_interface_macaddr wan'  "$HOOK"; then
	ok "hook sets both lan and wan interface macaddr"
else
	bad "lan+wan coverage" "expected macaddr on both lan and wan"
fi

# 3. config_generate must still consume network.<iface>.macaddr.  If a future
#    change removes that, the hook silently stops working again.
if grep -q 'json_get_vars device macaddr' "$GEN" && \
   grep -q "network.@device\[-1\].macaddr" "$GEN"; then
	ok "config_generate consumes interface macaddr and emits a device entry"
else
	bad "config_generate consumer" "interface macaddr -> device macaddr path missing"
fi

# 4. The helper the hook calls must actually exist in this tree.
if grep -q '^ucidef_set_interface_macaddr()' "$HELP"; then
	ok "ucidef_set_interface_macaddr is defined locally"
else
	bad "helper defined" "ucidef_set_interface_macaddr not found in uci-defaults.sh"
fi

# 5. Regression guard for the specific RC1-HW-002 mistake: a hook that relies
#    ONLY on network-device has no effect here, because config_generate does not
#    iterate that object.
nd_only=$(grep -c 'ucidef_set_network_device_mac' "$HOOK" || true)
has_iface=$(grep -c 'ucidef_set_interface_macaddr' "$HOOK" || true)
if [ "$has_iface" -ge 1 ]; then
	ok "hook does not depend solely on the unread network-device object"
else
	bad "network-device dependency" "$nd_only network-device calls, 0 interface calls"
fi

# 6. The evaluated hook must produce macaddr entries for the production MACs.
#    Run the real hook body's primitive against a recorded board.json fragment
#    and assert the resulting json contains the interfaces with macaddr set.
TMPD=$(mktemp -d)
cat > "$TMPD/probe.sh" <<'PROBE'
. /lib/functions/uci-defaults.sh
. /lib/rt3000/mac.sh
PROBE
# Instead of sourcing (needs a live board), assert the mapping the hook uses is
# the frozen one by checking the derivation still yields the expected values.
. "$HERE/rt3000-mac.sh"
M=$(RT3000_ETHADDR_SOURCE=00:11:22:33:44:55 rt3000_mac_map 2>/dev/null)
L=$(printf '%s\n' "$M" | sed -n 's/^lan //p')
if [ "$L" = "9e:a7:ce:69:5e:6a" ]; then
	ok "derivation feeding the hook yields the frozen LAN MAC"
else
	bad "hook feed" "lan=$L"
fi
rm -rf "$TMPD"

# 7. Wi-Fi MACs follow a different pipeline from the wired ones: the wireless
#    config is generated by the mac80211 detect helper after board.d runs, so a
#    02_macaddr-only fix leaves the radios on their defaults.  Guard that a
#    uci-defaults step exists to write wireless.radioN.macaddr.
WIFIDEF="$TOP/target/linux/ipq50xx/base-files/etc/uci-defaults/99-rt3000-wifi"
if [ -f "$WIFIDEF" ]; then
	ok "Wi-Fi MAC uci-defaults step is packaged"
else
	bad "wifi uci-defaults" "missing $WIFIDEF"
fi
if [ -f "$WIFIDEF" ] && grep -Eq 'wireless\.\$(radio|section)\.macaddr|wireless\.radio' "$WIFIDEF"; then
	ok "Wi-Fi step writes wireless.radioN.macaddr (the key mac80211 reads)"
else
	bad "wifi macaddr key" "step does not set wireless.radioN.macaddr"
fi
# The mac80211 helper must still honour that key.
MWIFI="$TOP/package/kernel/mac80211/files/lib/wifi/mac80211.sh"
if grep -q 'config_get macaddr "$device" macaddr' "$MWIFI"; then
	ok "mac80211 helper still consumes wireless radio macaddr"
else
	bad "mac80211 consumer" "mac80211 no longer reads radio macaddr"
fi

echo
echo "==================================================="
echo "CONFIG_PATH_TESTS_PASS=$PASS"
echo "CONFIG_PATH_TESTS_FAIL=$FAIL"
if [ "$FAIL" -eq 0 ]; then
	echo "CONFIG_PATH_TESTS=PASS"
else
	echo "CONFIG_PATH_TESTS=FAIL"
	printf '%s\n' "$FAILED"
fi
echo "==================================================="
[ "$FAIL" -eq 0 ]
